#pragma config(Motor,  port2,           towerLowerLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           towerUpperRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           towerLowerRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           towerUpperLeft, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 10;

void armMotor(int speed) {
	motor(towerUpperLeft) = speed;
	motor(towerLowerLeft) = speed;
	motor(towerUpperRight) = speed;
	motor(towerLowerRight) = speed;
}

task main() {
	while (true) {
		int input = (vexRT[Ch2]);

		if (abs(input) <= threshold) {
			armMotor(0);
		} else if (input > 0){
			armMotor(input);
		} else if (input < 0) {
			armMotor(input/10);
		}

	};
}
