#pragma config(Motor,  port1,           Gun,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           TowerUp,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           TowerDown,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftRear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightRear,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Intake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
#pragma DebuggerWindows("vexCompetitionControl")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#include "helper.c"
#include "chassis.c"
#include "gun.c"
#include "tower.c"
#include "intake.c"
#include "claw.c"
#include "lcd.c"
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

task main()
{
  startTask(chassis_control);
  startTask(gun_control);
  startTask(tower_control);
  startTask(intake_control);
  startTask(claw_control);
  //startTask(lcd_control);

  while (true)
  {
    //checkAutonomous();
  	//printSensorValuesToDebugWindow();
    wait1Msec(100);
  }
}
