#pragma config(Sensor, in1,             AutonSelector, sensorPotentiometer)
#pragma config(Motor,  port1,           Gun,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           TowerUp,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           TowerDown,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftRear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightRear,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Intake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
#pragma DebuggerWindows("vexCompetitionControl")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "helper.c"
#include "sensor.c"
#include "chassis.c"
#include "gun.c"
#include "tower.c"
#include "intake.c"
#include "claw.c"
#include "lcd.c"
#include "auton_basic.c"
#include "auton1.c"
#include "auton2.c"
#include "auton3.c"
#include "auton4.c"
#include "autonSkills1.c"
#include "autonSkills2.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

task autonomous() {
  int mode = get_auton_mode();
  if(mode == 1) {
    auton1();
  } else if(mode == 2) {
    auton2();
  } else if(mode == 3) {
    auton3();
  } else if(mode == 4) {
    auton4();
  } else if(mode == 5) {
    autonSkills1();
  } else if(mode == 6) {
    autonSkills2();
  }
}

task usercontrol() {
  startTask(chassis_control);
  startTask(gun_control);
  startTask(tower_control);
  startTask(intake_control);
  startTask(claw_control);
  startTask(lcd_control);

  while (true)
  {
    //checkAutonomous();
    //printSensorValuesToDebugWindow();
    wait1Msec(100);
  }

}
