#pragma config(Motor,  port1,           tower,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 5;

task main()
{
	while (true) {
		remoteInput = vexRT[Ch2];
		motor[tower] = abs(remoteInput) > threshold ? vexRT[Ch2] : 0;
	}
}
