#pragma config(Motor,  port1,           tower,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 5;

task tower_control()
{
	while (true) {

	}
}
